relecov_tools/config_json.py, relecov_tools/schema/relecov_schema.json
- Schema has being ordered by classification
- Enums were left in a bunch of properties, they have being filled with enums in metadata_lab_v3.0.xlsx form
- Duplicated properties have been deleted
- Public databases classification has been added and only identifiers are left for ENA and gisaid in the schema.
- Minor fixes: added examples, fixed typos and added descriptions.
*FIXES TODO*
- Anatomical_material, environment_system and environment_material properties don't have same enums in metadata_lab excel and the json schema. I think they are correct in the excel, but I remember we simplified anatomical material in the excel but it was divided in two fields according to the ontology we used. @ErikaKvalem can we check this?
-
=> Fixes relecov schema v1.0.0

relecov_tools/__main__.py, relecov_tools/feed_database.py, relecov_tools/read_lab_metadata.py, relecov_tools/schema/relecov_schema.json
- Change in read_metadata_lab the field where the schema name is collected 
- Remove the option that the schema could be different that the one in the tools
- specimen_source, moved the classification text to description and set in classification Sample collection and processing
=> Fixed bug in schema name and remove option to get other schema for feed database

relecov_tools/conf/anatomical_material_collection_method.json, relecov_tools/conf/configuration.json, relecov_tools/conf/geo_loc_cities.json, relecov_tools/conf/laboratory_address.json, relecov_tools/conf/submitter_address.json, relecov_tools/read_lab_metadata.py, relecov_tools/sftp_handle.py
In order to simplify some parts of the code and to be make it more flexible to different options, many changes were made:
1) The first step was to replace  '_ _ all _ _' as a field possibility for the actual fields that compose the mapped field in [configuration.json](https://github.com/BU-ISCIII/relecov-tools/blob/develop/relecov_tools/conf/configuration.json) 
2) To make it functional, not only a few changes were made in the process_from_json and adding_fields methods from [read_lab_metadata.py](https://github.com/BU-ISCIII/relecov-tools/blob/develop/relecov_tools/read_lab_metadata.py), but also the structure of [laboratory_address.json](https://github.com/BU-ISCIII/relecov-tools/blob/develop/relecov_tools/conf/laboratory_address.json) and …
=> Changes in the json files related with read-lab-metadata.py along with adaptations of the code to the new structure

relecov_tools/__main__.py, relecov_tools/conf/configuration.json, relecov_tools/long_table_parse.py, relecov_tools/sftp_handle.py
To fit the goal of the title I did some changes in:
1. [configuration.json](https://github.com/BU-ISCIII/relecov-tools/blob/develop/relecov_tools/conf/configuration.json): changed "storage_local_folder" field name in "stfp_handle" and removed "tmp_metadata_folder" as it has no use now. I also found out some bugs related to wrong column names in "metadata_lab_heading" field so i deleted them too.
2. [sftp_handle.py](https://github.com/BU-ISCIII/relecov-tools/blob/develop/relecov_tools/sftp_handle.py): I deleted "metadata_tmp_folder" as everything is now going to be downloaded and processed in the same location. Also adapted self.storage_local_folder to the new field name in config file. In the process I encountered some bugs related to ad-hoc expected positions in …
=> Changed sftp_handle to download everything in the output location.

relecov_tools/__main__.py, relecov_tools/conf/configuration.json, relecov_tools/sftp_handle.py
The objective of this PR is to introduce tools that can be used to clean the remote sftp server.
To accomplish this goal, I introduced a new option "download_option" in [__main__.py](https://github.com/BU-ISCIII/relecov-tools/blob/develop/relecov_tools/__main__.py)'s download function. The three download options are: download_only, download_clean and delete_only. They can be used along with --target_folders to select which folders will be processed.
- download_only will only download the files
- download_clean will remove files from sftp after download 
- delete_only will only delete the files,
As a ways to reduce the number of lines in the code, I introduced these options in [configuration.json](https://github.com/BU-ISCIII/relecov-tools/blob/develop/relecov_tools/conf/configuration.json) …
=> Included new functionalities in download process to clean sftp server

relecov_tools/conf/geo_loc_cities.json, relecov_tools/conf/laboratory_address.json, relecov_tools/json_validation.py, relecov_tools/read_lab_metadata.py, relecov_tools/sftp_handle.py
Download function was deleting the local folder even when the selected output location was an existing folder with files. Therefore, I changed the way `local_folder_path` is set in `get_files_from_sftp_folder` function from [sftp_handle.py](https://github.com/BU-ISCIII/relecov-tools/blob/develop/relecov_tools/sftp_handle.py) along with small print changes and a new error handler that I had to include for debugging and an overall cleaning of redundant functions. 
I also included additional info into the validation report message from [json_validation.py](https://github.com/BU-ISCIII/relecov-tools/blob/develop/relecov_tools/json_validation.py) and changed a print that was repeated in two different functions to ease debugging in [read_lab_metadata.py](https://github.com/BU-ISCIII/relecov-tool …
=> Changed local path for sftp_handle.py and introduced additional debug info

relecov_tools/conf/configuration.json, relecov_tools/gisaid_upload.py, relecov_tools/sftp_handle.py, relecov_tools/utils.py
[sftp_handle.py](https://github.com/BU-ISCIII/relecov-tools/blob/develop/relecov_tools/sftp_handle.py) was not verifying the md5 values of the remote files correctly so it had to be fixed. Moreover, I included several testings to extract data from three possible md5checksum configurations: The one from linux `md5sum * > md5checksum.csv` another one from windows which includes headers ("Hash" and "Path") and windows paths (meaning "\" instead of "/") and a last one that has asterisks before the paths coming from third-party softwares.
I also included handling of uncompressed files in order to reduce the space occupied by these downloaded files, and made the code more robust on a general basis by including better error handling and retries for corrupted files (which were previously skipped …
=> Big changes in sftp_handle.py and minor in utils.py and configuration.json

.github/workflows/test_modules.yml, .github/workflows/test_sftp_handle.yml
As per the title, there were errors in the tests due to a weird functionality in `actions/checkout` related to `pull_request` option. When this option was activated, the tested code was the one from the repository receiving the pull request instead of the proper code that is going to be merged as seen in [numerous issues](https://github.com/actions/checkout/issues/881). 
I included the changes found in the [documentation](https://github.com/actions/checkout/blob/v3.0.2/README.md#user-content-checkout-pull-request-head-commit-instead-of-merge-commit) related to these issues.
Also, for better security, I only used `pull_request_target` when necessary (sftp_handle tests)
=> Splitted tests in two files, fixed pull-request checkout error

relecov_tools/log_summary.py, relecov_tools/read_lab_metadata.py, relecov_tools/sftp_handle.py
I created a new module that can be used in every process to create a custom Log report in Json format, This PR also includes its functionalities in sftp-handle and read-lab-metadata, which also received several improvements in error handling.
The changes in read-lab-metadata include the rejection of conflicting fields, so they are not included in the output processed Json file. Therefore, this enables the recognition of not provided fields by the validation module and Closes #250 
Moreover, now sftp-handle's download module pre-merges multiple metadata files in remote repository if they are found in the same folder prior to merging those from different folders.
This also closes #245
=> Introduced log_summary module for custom logs. Improvements in read-lab and excel-merging in sftp_handle

relecov_tools/sftp_handle.py, relecov_tools/upload_ena_protocol.py, relecov_tools/utils.py
As per the title, last PR created a bug that left a temporary folder in remote's home location. Which is fixed in this PR along with minimal changes in utils.read-excel() when no header flag is found and import pdb() removals in upload-to-ena
=> Hotfix for tmp folder creation in remote home

relecov_tools/log_summary.py, relecov_tools/read_lab_metadata.py
Appart from a small fix in read_lab_metadata (Now when an invalid date is met is doesn't crash, just continues), now the output json file with the custom log from json_summary.py includes the name of the module called (e.g. if its generated from a read-lab-metadata call, the output name will be `DATE_read_lab_metadata_log_summary.json`
=> Now json_summary custom log filename includes module called

relecov_tools/json_validation.py
As per the title, with these changes the validation module will create a separate json file called `"validated_***_metadata.json"` which will only include those samples that were successfully validated, Closes #274
=> Validate module now creates a validated metadata json file

relecov_tools/sftp_handle.py
This PR includes several changes to download module to improve its functionalities:
- Cleaning process after download now skips sequencing files left in remote repository due to validation failure
- Temporary files are correctly removed from local folder
- Better logs overall, more info is included (such as processed folders and corrupted files)
- No `output_location/downloaded_folder/$DATE/` folder is created inside the downloaded folder as `tmp_processing_DATE` already includes the date
=> Better sftp cleaning and download logging

relecov_tools/read_lab_metadata.py
As per the title, some dates were not correctly being processed in read-lab-metadata. This PR fixes it
=> Hotfix for invalid date check in read-lab-metadata

relecov_tools/__main__.py, relecov_tools/conf/configuration.json, relecov_tools/upload_database.py
Configuration was changed to have parameters defined for upload_module under upload_module.
Change on code to apply this and fixing errors when upload data to iSkyLIMS.
=> upload database module updated

relecov_tools/assets/pipeline_utils/viralrecon.py, relecov_tools/conf/bioinfo_config.json
As per the title, I included a (in my opinion, messy) way to extract pango-data version and include it in the metadata when read-bioinfo-metadata is used for viralrecon. I call it messy because it revolves completely in our internal folder structure and won't work if that folder structure is changed.
=> Included pango-data version extraction in read-bioinfo-metadata

CHANGELOG.md, README.md, relecov_tools/__main__.py, relecov_tools/json_validation.py, relecov_tools/log_summary.py
Now `json_validation.py` also creates an excel file with the logs from the validation process. The excel file includes two sheets, one with errors and the other one with warnings. Each sheet has three columns, the first corresponds with `sequencing_sample_id`, the second indicates if the sample was valid or not, and the third is the content of the logs (either errors or warnings, depending on the sheet).
Closes #283
=> log_summary creates an excel file from logs

CHANGELOG.md, relecov_tools/assets/pipeline_utils/viralrecon.py, relecov_tools/conf/bioinfo_config.json, relecov_tools/read_bioinfo_metadata.py, relecov_tools/utils.py
In-depth description:
- Now before starting with data processing, `j_data` is separated into smaller copies, according to `r1_fastq_filepath` unique values found in the samples and all the process is iterated over each of these set of samples.
- `output_folder` is now a mandatory arg to include in each method called by the auxiliar script (in this case `viralrecon.py`). This was needed in order to extract `long_table*.json ` file to its respective batch folder
- `handling_tables()` is a now separated from `handling_files()` as an independent method, just for readability
- Changed file pattern matching to `sequencing_sample_id` as now `pipeline_manager` names files using that field.
- Each validated file is now extracted during `add_bioinfo_files_path()`
- Included two new fields in …
=> Now read-bioinfo-metadata splits data and extract files for each batch

.github/workflows/pypi_publish.yml, .github/workflows/test_modules.yml, .github/workflows/test_sftp_handle.yml, CHANGELOG.md, relecov_tools/__main__.py, setup.py
This PR prepares for release 1.1.0
- Included a sleep time in test_sftp-handle to avoid concurrency check failure (sometimes a process would start even though another one was active)
- Fixed failing module_tests.yml workflow due to deprecated upload-artifact version
- Changed pypi_publish action to publish on every release, no need to push tags anymore
=> Pre-release 1.1.0. Includes fixing github actions

CHANGELOG.md, relecov_tools/download_manager.py, relecov_tools/pipeline_manager.py, relecov_tools/sftp_client.py
This PR includes the following changes:
For download_manager:
- Now single logs summaries are also created for each folder
- Fixed wrong single-paired layout detection in metadata due to Capital letters
- More accurate cleaning process, skipping only sequencing files instead of whole folder
- Now skips remote folders named "invalid_samples" as they are already processed
- Hotfix for wrong dict processing that would lead to a crash when any file failed validation using the given md5 in an md5sum file 
- Sftp_client.py: Removed first sleep time for reconnection decorator, sleep time now increases in the second attempt
Pipeline_manager:
- Introduced handling for missing/dup files and more accurate information in prompt
=> Hotfix for download_manager & enhancements for pipeline-manager

relecov_tools/__main__.py, relecov_tools/dataprocess_wrapper.py, relecov_tools/json_validation.py, relecov_tools/log_summary.py, relecov_tools/read_lab_metadata.py, relecov_tools/utils.py
This PR includes a new module temporarily called "wrapper" which executes **download**, **read-lab-metadata** and **validate** processes consecutively for each downloaded set of samples. This simplifies the processing workflow as all the provided metadata is validated and a report is generated including all the errors found for each sample which can be sent via email to the corresponding submitter.
Along with this new module come several changes in related modules:
- Those log_summary messages which previously included any field from the schema now include the label instead, as it's what the submitter will see in the xlsx template.
- The excel log report created by `logs-to-excel` now has a cell size adjustment step for large messages
- Multiple error handlings for merge_logs() and …
=> New wrapper module & changes in logs reporting

CHANGELOG.md, relecov_tools/log_summary.py
Just what the title says. Logs-to-excel did not handle logs with multiple main_keys (labs) and did not include the global logs, just logs associated to samples. Now a sheet called "Global Report" includes this generic information of the process.
=> Logs-to-excel accepts multiple keys and includes folder logs

CHANGELOG.md, relecov_tools/__main__.py, relecov_tools/download_manager.py, relecov_tools/read_lab_metadata.py
This pull request introduces a `files-folder `argument to specify the location of sample files when no `samples_data.json` file from download module is provided, enhancing the flexibility of the read-lab-metadata function. It also improves logging, adding messages for cases of duplicate sample IDs and missing files, while handling metadata and file path validation more robustly. The changes streamline error handling and user feedback, making the tool more resilient and user-friendly.
=> New files-folder argument and mproved logging messages for read-lab-metadata

.github/workflows/python_lint.yml, CHANGELOG.md
As per the title, github workflow 'python_lint.yml' was still waiting for .py files in the PR, this is now fixed
=> Fixed linting was still waiting for .py files

CHANGELOG.md, README.md, relecov_tools/__main__.py, relecov_tools/log_summary.py, relecov_tools/read_lab_metadata.py, relecov_tools/utils.py, setup.py
Changes in the pre-release:
Version has already been updated for the release.
Some hotfix that were needed for the release:
- Now files-folder arg works with relative paths in read-lab-metadata
- Homogeneized style of report global report sheet with the rest of the sheets when logs-to-excel is used (also within wrapper)
- Included a try-except for every module to catch unexpected errors, this is needed to catch any unexpected errors to the log-file that may lead the process to crash.
- Now check-gzip-integrity() catches any exception instead of just the (previously expected to be the only possible error) gzip.BadGzipFile error. This makes some sense as that method is only expected to return True when no exceptions are raised, meaning that the file integrity is intact and it can be …
=> Pre-release 1,3,0

relecov_tools/__main__.py, relecov_tools/download_manager.py
- We move forward the gzip compression check.  
- Corrupted files are removed from "clean_fetchlist" before checking if they are in "successful_files."  
- If the samples are corrupted, instead of moving them to a corrupted folder, both R1 and R2 are deleted from the folder to request them again.
- Added relecov-tools version to log
Fixes issue #344
Partially fixed issue #336
=> Fixed some issues in download module

CHANGELOG.md, relecov_tools/__main__.py, relecov_tools/json_validation.py
Validate module was crashing when no "METADATA_LAB" sheet was found in the excel file. This PR addresses it by adding a new optional argument, aswell as taking the default value from the config file.
=> Fixing validate crashing with new sheet names

CHANGELOG.md, relecov_tools/__main__.py, relecov_tools/log_summary.py, relecov_tools/mail.py, relecov_tools/templates/jinja_template_with_errors.j2
Added param to pass template path
- Added email password that was being unused
- Explained help better
- Added samples's batch number
- Added invalid_samples folder explanation
- Added minor fixed to e-mail template
- Fixed log2excel error
=> Fixed email module

CHANGELOG.md, relecov_tools/assets/pipeline_utils/viralrecon.py, relecov_tools/conf/bioinfo_config.json, relecov_tools/read_bioinfo_metadata.py
- Made long table to be written in `--outdir`. Fix issue #351 
- Fixed module to find files not containing sample_name in filename (`viralrecon_filepath_mapping_stats`, `viralrecon_filepath_summary_mqc`, `viralrecon_filepath_variants_long_table`, `viralrecon_filepath_workflow_summary`)
- Added year to `--outdir` to write files
- Added batchID/date to filename instead of current date for `--oudir` and `--batchdir`
- Added current date for tables written in `analysis_results`
- Test whether `variants_long_table `and `bioinfo_lab_metadata `already exist and try to merge new samples, ignores samples already existing that contain exactly the same info.
- Write long table only with samples in the COD to COD folder
=> Fixed read-bioinfo-metadata module

CHANGELOG.md, relecov_tools/assets/pipeline_utils/viralrecon.py, relecov_tools/conf/bioinfo_config.json, relecov_tools/read_bioinfo_metadata.py, relecov_tools/schema/relecov_schema.json
A new field has been implemented to the lab metatada json that defines if the selected/generated QC values meet the established thresholds.
=> Added Quality Control functionality to read-bioinfo-metadata module

CHANGELOG.md, relecov_tools/build_schema.py
A drop-down has been added to "METADATA_LAB" sheet for those properties that have enums to facilitate user selection.
This PR tries to solve [issue 291](https://github.com/BU-ISCIII/relecov-tools/issues/291)
=> Added drop-down functionality to build-schema

CHANGELOG.md, relecov_tools/conf/bioinfo_config.json, relecov_tools/utils.py
Read-bioinfo-metadata was parsing integer IDs as floats sometimes, I changed an utils.py function to make it more consistent with datatypes.
Also changed  "quality_control" key "required" to False in bioinfo_config.json until a way to obtain this data is implemented in buisciii-tools
=> QC is not required in bioinfo_config until its implemented. Fixed datatypes

CHANGELOG.md, relecov_tools/build_schema.py, relecov_tools/json_validation.py, relecov_tools/read_lab_metadata.py
This PR improves `build-schema` and `read-lab-metadata` modules:
- Implemented interpretation of "options" column in orther to add this fields to its property.
- Enhanced field typing while creating lab_metadata json on read-lab-metadata-module
=> Improve "options" interpretation in `build-schema` and update `read-lab-metadata` field type

CHANGELOG.md, relecov_tools/build_schema.py
This PR improves the `validate_database_definition` method with several enhancements to ensure better schema validation and error reporting:
- Checks for duplicated enums
- Checks for date format complance
- Generates a structured error report and saves it in csv
Related (#381 )
=> Enhance  validation of database definitinon values

CHANGELOG.md, relecov_tools/build_schema.py
Previously, the schema was generated only when the `--diff` parameter was specified on the command line. 
The evaluation of differences with respect to the base schema and the generation of the new schema have been separated.
=> Fix schema generation dependence on --diff parameter (`build-schema` module)

CHANGELOG.md, relecov_tools/conf/configuration.json, relecov_tools/read_lab_metadata.py
This PR enhances the `read-lab-metadata` module by implementing automatic filling of `tax_id` and `host_disease` fields according to the `organism` value.
Key Changes:
- Added a new organism_mapping field to `configuration.json` to define the relationships between `organisms`, `tax_id`, and `host_disease`.
- Updated the `add_fixed_fields` function in the `read-lab-metadata` module to apply the organism_mapping logic.
=> Update `read-lab-metadata` module: Auto-fill `tax_id` and `host_disease` based on organism

CHANGELOG.md, relecov_tools/__main__.py, relecov_tools/conf/configuration.json, relecov_tools/json_validation.py, relecov_tools/pipeline_manager.py, relecov_tools/read_bioinfo_metadata.py, relecov_tools/read_lab_metadata.py, relecov_tools/upload_ena_protocol.py, relecov_tools/utils.py
With this PR pipeline-manager functionality is enhanced to also select the necessary pipeline template for each sample depending on the organism analyzed. As a starting point, 3 organisms are included in `configuration.json`, but that can be increased in further implementations.
Closes #402
=> Pipeline-manager now splits samples by organism-template first

CHANGELOG.md, README.md, relecov_tools/__main__.py, relecov_tools/build_schema.py
The module has been updated with a new `--non-interactive` parameter that executes the module by assigning default values for automatic execution.
On the other hand, the `README` has been updated with the new implemented parameters and their explanations.
=> Add non-interactive mode to build-schema module

.github/workflows/test_sftp_modules.yml, CHANGELOG.md
This PR removes the wrapper testing step from the GitHub Actions workflow in `relecov-tools`. The decision was made because the wrapper fails to log in to the SFTP server, causing a time-out and preventing the workflow from completing successfully.
Changes:
Removed the `wrapper testing` step from the GitHub Actions workflow.
=> Remove `Wrapper` Testing from GitHub Actions Workflow

.github/workflows/test_sftp_modules.yml, CHANGELOG.md, tests/test_wrapper_handle.py
This PR aims to verify whether updating the port assignment via wrapper_manager allows successful SFTP login when running test_wrapper in GitHub Actions.
**Changes:**
- Updated the port assignment method in wrapper_manager.
- Triggered test_wrapper in GitHub Actions to check if the SFTP authentication issue is resolved.
=> Test SFTP Login by Updating Port Assignment in `wrapper_manager`

CHANGELOG.md, relecov_tools/assets/schema_utils/custom_validators.py, relecov_tools/json_validation.py
This update enhances the JSON Schema validation process by allowing the string "Not Provided" as a valid input for numeric fields (integer, number) and date-formatted strings (string, format: date). The new implementation integrates validate_with_exceptions(), which filters out specific type errors while ensuring all other validation rules remain enforced. This approach maintains strict schema validation while introducing flexibility for missing values, improving data handling without modifying the schema structure.
Closes #425
=> Added custom validator to extend validation exceptions

CHANGELOG.md, relecov_tools/__main__.py, relecov_tools/mail.py, relecov_tools/templates/jinja_template_results.j2, relecov_tools/upload_results.py, requirements.txt
This PR introduces the `upload_results` module, which automates the process of uploading batch results to their respective COD folders. The module performs the following tasks:
- Identifies the CODs processed in a given batch.
- Compresses the analysis_results folder with password protection.
- Uploads the compressed file to the SFTP server.
- Sends an email notification to the laboratory, including details of the uploaded results and the password to access the compressed file.
=> New module for uploading to the SFTP the results of a batch

CHANGELOG.md, relecov_tools/read_bioinfo_metadata.py
Currently the path was generated according to the path included in the --out_dir option but it should really be generated according to the point where the module is executed.
=> Fix viralrecon_filepaths Path in `read-bioinfo-metadata` Module

CHANGELOG.md, relecov_tools/read_lab_metadata.py
As it is right now `read-lab-metadata` if the value has no ontology the module tries to add it. But it does this all the time and fails when the enum has no ontology and tries to add one (which it doesn't have).
=> Fix adding_ontology_to_enum when enum has no ontology

relecov_tools/__main__.py, relecov_tools/read_bioinfo_metadata.py
- **Fixed issue**: The `Read-bioinfo-metadata` function now properly prevents output generation when no matching samples are found by implementing the `validate_samplenames` method.
- **New feature**: Added a `--debug` flag to enhance troubleshooting capabilities by providing more detailed logs.
- Closes #267
=> Fix no matching samples read bioinfo and add debug flag

CHANGELOG.md, relecov_tools/__main__.py, relecov_tools/conf/configuration.json, relecov_tools/upload_results.py
As per the title, this PR introduces some changes on the `upload_results` module, by changing the config file, replacing all `sys.exit(1)` instances by `raise` and by handling exceptions properly in the `upload_results` function from `__main__.py`.
Closes #252.
=> Fixed some pending issues for the creation of the new SFTP module

CHANGELOG.md, relecov_tools/assets/pipeline_utils/viralrecon.py, relecov_tools/read_bioinfo_metadata.py
This PR introduces two key fixes to the `read-bioinfo-metadata` module:
**Changes:**
Evaluate qc_test at Batch Level:
- The evaluation of the `qc_test` flag is now correctly performed for each batch.
- This ensures that the quality control assessment is consistently reflected in both the batch-level bioinfo files and the central update_db output.
Handle Non-Evaluable %LDMutations:
- The function was updated to properly handle cases where `%LDMutations` is set to `"Not Evaluable [NCIT:C186292]"`.
=> Fix `read-bioinfo-metadata`: Evaluate `qc_test` at Batch Level and Handle `Non-Evaluable` %LDMutations

CHANGELOG.md, relecov_tools/__main__.py, relecov_tools/read_bioinfo_metadata.py
This PR introduces a new `--update` flag in the `read-bioinfo-metadata` module to support conditional updates of existing metadata files. When enabled, the module will compare the new metadata being generated with the already existing file and allow the user to interactively confirm updates where discrepancies are found.
=> Add `--update` Flag to Allow Metadata Update in `read-bioinfo-metadata` Module

CHANGELOG.md, README.md, relecov_tools/conf/bioinfo_config.json, relecov_tools/read_bioinfo_metadata.py, relecov_tools/schema/ena_schema.json
This PR addresses issue [#453] by improving how the read-bioinfo-metadata module handles warnings related to:
1. `.gz` Compressed Files
2. variants_long_table.csv mapping
=> Improve Warning Handling for `.gz` Files and `variants_long_table.csv` in `read-bioinfo-metadata`

CHANGELOG.md, pyproject.toml, relecov_tools/upload_database.py
Right now update-db fails for non-string fields, which is fine since relecov-platform forces most fields to charfields. This PR creates a temporal workaround by converting all fields in json data to strings
=> Hotfix for non-string fields in json data

CHANGELOG.md, relecov_tools/log_summary.py
This PR improves the formatting of the Global Report sheet in the summary Excel by truncating overly long warnings and errors individually, preventing excessively large or unreadable cells (e.g., enum lists with thousands of items).
Before: 
After: 
---
Closes(#469)
=> Truncate long warnings individually in Global Report

CHANGELOG.md, relecov_tools/sftp_client.py
This PR reverts the changes applied in #483 
This error was correctly addressed in the remote sftp and the hotfix is no longer necessary
=> Reverted temporal hotfix for corrupted sftp folders 

CHANGELOG.md, relecov_tools/base_module.py
This PR addresses an error in BaseModule that arose when redirecting logs to a different machine, as the copied files retained their original permissions, leading to a somewhat confusing OSError
Closes #477
=> Fixed permissions error between different machines #477

CHANGELOG.md, relecov_tools/__main__.py, relecov_tools/base_module.py, relecov_tools/dataprocess_wrapper.py
This PR fixes an small error that was leading to logs from subprocesses to go in wrapper's output_location instead of its own defined output_locations (either via config or by default).
Closes #490
=> Fixing subprocess logs going in wrapper output_location instead of its own

CHANGELOG.md, README.md, relecov_tools/__main__.py
This PR standardizes the name of the CLI option used to specify the JSON Schema in the `validate` command.
Closes (#499) Inconsistent option name between CLI help and wrapper config for json_schema
=> Unify CLI Option Name for JSON Schema Validation

CHANGELOG.md, relecov_tools/__main__.py
- Clarified misleading "All provided files were empty" message when lab_code is not found.
- Added check for empty input files with a proper error message.
Closes #506
=> Improve error handling and messages in `logs-to-excel` module

CHANGELOG.md, relecov_tools/dataprocess_wrapper.py
As per title, statistics about the number of laboratories analysed, the total number of files processed, and the number of files processed by each laboratory have been collected and logged. This information is visible through on-screen text, as well as collected in the wrapper log file.
Closes #468
=> Added summary stats logging to wrapper module

CHANGELOG.md, relecov_tools/download_manager.py
=> Fixed paired and single-end files validation #535

CHANGELOG.md, relecov_tools/__main__.py, relecov_tools/config_json.py
=> Suppressed unrelated warning when extra-config is not set

CHANGELOG.md, relecov_tools/read_bioinfo_metadata.py
- New log functionality is now correctly handled in read-bioinfo-metadata, as it was generating two logfiles due to a repeated init of BaseModule class in BioinfoLogReport(). Closes #533 
- Fixed deprecated `sequence_file_path_R1_fastq` for the newer version `sequence_file_path_R1`. Closes #545
=> Enhanced new log handling in read-bioinfo-metadata. Fixed deprecated r1_path field

CHANGELOG.md, relecov_tools/read_lab_metadata.py
Prior to this PR, when the organism field was left empty, a warning was raised informing that an `Unknown` metadata did not belong to a group of enums.
The metadata "Unknown" has been replaced for "Missing" in host_disease field when organism is empty. "Missing" is one of de available enums.
Now, the only warning printed is Organism: `XX samples failed validation for organism:\n'Organism' is a required property`.
Closes #519
=> Fixed unexpected warning message when `organism` field is empty.

CHANGELOG.md, relecov_tools/__main__.py, relecov_tools/dataprocess_wrapper.py, relecov_tools/log_summary.py
Closes https://github.com/BU-ISCIII/relecov-tools/issues/536
- **change log feed into excel behaviour, now handles one or several labs in the same excel depending on the info in the log**
- **homogeneize report metadata excel and json naming when using logs-to-excel to be the same as in wrapper**
=> Improve json to excel generation

.github/PULL_REQUEST_TEMPLATE.md, CHANGELOG.md, relecov_tools/assets/pipeline_utils/viralrecon.py
This PR introduces the following updates:
- Support for qc_failed logic in viralrecon.py:
The module now parses and evaluates the qc_failed expression defined in the schema to determine whether a sample fails quality control.
Example supported expression:
`"qc_failed": "(per_sgene_coverage < 98.0) -- (per_ldmutations < 60.0)"
`
The expression supports logical grouping using -- as a separator for multiple conditions, evaluated as logical OR.
- PR Template Updated
=> Add support for `qc_failed` logic in `viralrecon.py` and update `PR template`

CHANGELOG.md, relecov_tools/json_validation.py, relecov_tools/log_summary.py
- Applied truncation to error and warning messages longer than 250 characters in the `validate_instances` method.
- Ensured both `stderr.print` output and entries added via `logsum.add_warning` are properly truncated to prevent overflow in terminal reports and emails.
- Preserved full error context in individual sample logs (i.e., `logsum.add_error`) while keeping the summary concise
----
Closes(https://github.com/BU-ISCIII/relecov-tools/issues/517)
=> Truncated Sample-Level error messages in global report and terminal.

CHANGELOG.md, relecov_tools/download_manager.py
=> Hotfix for folder specific download log_summary filename

CHANGELOG.md, relecov_tools/dataprocess_wrapper.py, relecov_tools/download_manager.py
RELECOV has been set as the default subfolder. In this way we avoid that this variable could be left empty and, therefore, we avoid associated troubles during the download.
Closes #508
=> Set default folder as RELECOV when running wrapper module

CHANGELOG.md, relecov_tools/upload_results.py
This PR fixes the return behavior of the upload-results module and updates the configuration loading mechanism to ensure proper handling of mail and SFTP configurations.
=> Fix return values and configuration handling in `upload-results` module

CHANGELOG.md, relecov_tools/base_module.py
=> Hotfix for level and cli-logpath outdir in BaseModule

CHANGELOG.md, relecov_tools/assets/pipeline_utils/irma.py, relecov_tools/assets/pipeline_utils/viralrecon.py, relecov_tools/pipeline_manager.py, relecov_tools/read_bioinfo_metadata.py
=> Included hex code in output filenames from bioinfo pipeline_utils scripts

CHANGELOG.md, relecov_tools/read_bioinfo_metadata.py
in #578 a new regex for div was added to make it work with taxprofiler. in viralrecon wasn't working propperly depending on the multiqc.html file.
Fixed this by adding a soup.find_all and another iteration
=> fixed parsing of multic software versions

CHANGELOG.md, relecov_tools/conf/configuration.json, relecov_tools/upload_database.py
=> Hotfix for update-db module in config urls and json_file call

CHANGELOG.md, relecov_tools/upload_database.py
This PR cleans up legacy logic in the `upload_database` module by removing the hardcoded fallback for `sample_entry_date` and the default assignment of `sample_type` when `specimen_source` is missing. These fields are now handled via proper ontology mapping or fixed configuration values. This improves consistency and prevents incorrect or redundant data from being sent to iSkyLIMS.
=> Clean up legacy fallback logic in upload_database mapping

CHANGELOG.md, relecov_tools/upload_results.py
After compressing the analysis_results folder and uploading it back to the sftp, the compressed file located in the local folder is now removed.
Closes #608
=> Added zip file removal step in upload_results module

CHANGELOG.md, relecov_tools/__main__.py, relecov_tools/log_summary.py
=> Now log_summary can merge logs with multiple keys, not for only provided lab-code

CHANGELOG.md, README.md, relecov_tools/upload_results.py, requirements.txt
We have modified the way in which the `analysis_results` folder is compressed and encrypted in order to make it easier for users to read and decompress it. AES (Advanced Encryption Standard) encryption has been replaced by the use of the 7z software, which generates files with 7z extension compatible and recognizable by windows and linux. The compressed file now requests the password on double-click, and no longer displays error messages.
Closes #582
=> Modified compression function in upload_results module to use 7z instead of AES-ZIP

CHANGELOG.md, relecov_tools/__main__.py, relecov_tools/build_schema.py
This PR closes #647 by improving error handling and execution flow in the metadata module.
- Fixed an issue where no message was printed to stdout/stderr when an exception was raised, making debugging harder.
- Fixed logic to ensure that example entries are not silently skipped when empty — now they are properly validated or reported.
=> closes #647 by fixing a logging inconsistency and updating versioning

CHANGELOG.md, relecov_tools/dataprocess_wrapper.py
=> Fix wrapper errors with no-invalid-samples and _RELECOV folders

CHANGELOG.md, relecov_tools/download_manager.py
This PR closes #642 by improving error reporting during metadata download.
- Added a clear error message when library_layout is missing in the metadata.
- The underlying issue was already fixed in [PR #619](https://github.com/relecov/relecov-tools/pull/619); this PR only adds explicit feedback to the user to improve traceability and usability.
=> Added error message in download when library layout is not provided in metadata

CHANGELOG.md, relecov_tools/json_validation.py
=> Restructured SchemaValidation so validate_instances can be a staticmethod

CHANGELOG.md, relecov_tools/assets/pipeline_utils/create_summary_tables.py
As per the title, the `create_summary_tables.py` script is updated so that, within the `surveillance_files` folder, an Excel file is created combining information for all analysed samples so far, along with a CSV file with all variant information for all samples and a subfolder called `consensus_files` (if indicated) containing `consensus.fa` files for all samples analysed so far. Therefore, information is generated for all samples together, instead of for each epidemiological week separately.
=> Updated `create_summary_tables.py` to organize data jointly

CHANGELOG.md, relecov_tools/__main__.py, relecov_tools/base_module.py, relecov_tools/build_schema.py, relecov_tools/conf/configuration.json, relecov_tools/download.py, relecov_tools/ena_upload.py, relecov_tools/gisaid_upload.py, relecov_tools/log_summary.py, relecov_tools/map.py, relecov_tools/metadata_homogeneizer.py, relecov_tools/read_bioinfo_metadata.py, relecov_tools/read_lab_metadata.py, relecov_tools/upload_database.py, relecov_tools/validate.py, tests/data/sftp_handle/configuration.json
This PR addresses Issue #230 by restructuring the `configuration.json` file to group fields into logical categories based on the tools or modules that use them. The aim is to improve readability, maintainability, and modular access throughout the relecov-tools codebase.
Grouped previously top-level fields into new high-level keys:
- general: general-purpose and shared settings
- read_lab_metadata: used by the read-lab-metadata module
- read_bioinfo_metadata: used by the read-bioinfo-metadata module
- upload_to_ena: settings for ENA metadata upload
- upload_to_gisaid: settings for GISAID metadata export
- upload_database: for internal database upload (e.g. iskylims, relecov)
- pipeline_manager: execution and grouping settings for analysis pipelines
- sftp_handle: already grouped (no …
=> Refactor `configuration.json` structure by grouping fields by `module usage`

CHANGELOG.md, relecov_tools/conf/configuration.json, relecov_tools/validate.py
=> Moved sample_id_ontology used by validate to configuration.json

CHANGELOG.md, relecov_tools/conf/configuration.json, relecov_tools/rest_api.py, relecov_tools/upload_database.py
=> Standardized RestApi response dictionaries with an aux function

CHANGELOG.md, relecov_tools/download.py
This PR fixes an edge-case in the download module where an empty target_folders value in extra_config.json caused the run to crash instead of defaulting to “process every COD folder.”
**What happened before**
```
"download": {
"target_folders": []    // or ""
}
```
The loader attempted to iterate over an empty list / string and raised a TypeError or ValueError, aborting the download.
=> Fix `"target_folders": ""` handling in `download` module

CHANGELOG.md, relecov_tools/assets/schema_utils/custom_validators.py, relecov_tools/conf/configuration.json, relecov_tools/read_bioinfo_metadata.py, relecov_tools/read_lab_metadata.py, relecov_tools/utils.py
This pull request performs a comprehensive refactor of the `read_bioinfo_metadata` module to improve clarity, structure, and maintainability, while preserving functionality.
- Refactored `__init__` method using internal auxiliary methods for improved modularity
- Reorganized initialization blocks and added inline comments for clarity
- Refactored `scan_directory` for improved readability and logic flow
- Simplified conditionals and renamed variables for consistency and clarity
- Added type annotations and detailed docstrings to new auxiliary methods
- Refactored `mapping_over_sample` for more transparent data handling
- Renamed and refactored `add_bioinfo_files_path` to `map_and_extract_bioinfo_paths`
- Refactored `add_bioinfo_results_metadata` and `create_bioinfo_files` to reduce …
=> Refactor read-bioinfo-metadata module

CHANGELOG.md, relecov_tools/rest_api.py
This PR improves the `RestApi.standardize_response()` method to ensure that when an API response does not include any of the expected `data` keys (`data`, `payload`, `result`), the remaining non-canonical keys are preserved under `result["data"]`.  
Previously, such responses resulted in an empty `data` object, even if the payload contained useful fields. Now, all keys except `message` and `error` (and their aliases) are captured as part of `data`, avoiding silent data loss.
=> Fix `data` completeness in `rest_api.standardize_response`

CHANGELOG.md, relecov_tools/download.py, relecov_tools/pipeline_manager.py, relecov_tools/rest_api.py
This PR fixes data handling as a list. Previously, when data was received, it remained empty.
Closses #763 #793 and #794.
=> Fix list handling in `rest_api.py`; Fix download invalid_folder processing; Fix pipeline-manager R1 check

CHANGELOG.md, relecov_tools/assets/pipeline_utils/create_summary_tables.py
As per the title, this PR fixes a bug in `create_summary_tables.py` so that csv variant files are created properly.
=> Fixed `create_summary_tables.py` to properly create variant files
