BU-ISCIII/relecov-tools

- sftp_download.sh
bash script to download sFTp directories
> Bash script to download sFTP directories

- relecov_tools/sftp_handled.py
- relecov_tools/utils.py
sftp module is tested, but missing to implement deletion on remote sftp
> sftp module

- relecov_tools/__main__.py
- relecov_tools/conf/configuration.json
- relecov_tools/sftp_handle.py
and also cleaning unnecessary  fields in configuration .json
> remove test parameter from sftp

- README.md
- relecov_tools/__main__.py
- relecov_tools/sftp_handle.py
- setup.py
> Updated readme

- README.md
> Some english misprints

- relecov_tools/conf/configuration.json
- relecov_tools/read_metadata.py
- relecov_tools/schema/relecov_schema.json
- relecov_tools/utils.py
renaming phage_plus to relecov 
and changes in relecov schema
> Update relecov schema

- relecov_tools/schema/relecov_schema.json
changed type from date to string
> fixing type value on analyis_data and lineage_identification_date

- relecov_tools/__main__.py
- relecov_tools/conf/configuration.json
- relecov_tools/feed_databases.py
- relecov_tools/map_schema.py
- relecov_tools/read_metadata.py
- relecov_tools/rest_api.py
- relecov_tools/test/test_cases.txt
Partial implementation for feed_database module. Only request to iSkyLIMS is done.
Pending testing code for this functionality
> Implemented feed database for iSkyLIMS

- relecov_tools/conf/geo_loc_cities.json
- relecov_tools/map_schema.py
- relecov_tools/schema/ena_schema.json
Updated with field changes for mapping to ENA
> changes with the mapping to ENA

- relecov_tools/__main__.py
- relecov_tools/conf/configuration.json
- relecov_tools/feed_database.py
- relecov_tools/schema/relecov_schema.json
Tested that json file from previous step is upload to iSkyLIMS
> Updated feed database module for sending data to iSkyLIMS

- relecov_tools/__main__.py
- relecov_tools/read_bioinfo_metadata.py
- relecov_tools/schema/relecov_schema.json
classification:
- fastq_r1', -> classification: Files info  to Bioinformatics and QC metrics fields
- 'fastq_r2', -> classification: Files info to Bioinformatics and QC metrics fields
- gene_name_1 -> classification: Bioinformatics and QC metrics fields  to Pathogen diagnostic testing
- 'sample_name', -> classification: "Files info" to "Bioinformatics and QC metrics fields"
> modified relecov_schema.json

- relecov_tools/utils.py
md5 was different from the one previously obtained. With this change, it is supposed to work properly
> corrected different md5 generation

- relecov_tools/metadata_homogeneizer.py
Looking good! Started the exception management - logging part
> Group 1, day 2 whole update

- relecov_tools/__main__.py
- relecov_tools/ena_upload.py
- relecov_tools/gisaid_upload.py
ena_upload.py : receipt.xml is saved in the the output_path
gisaid_upload.py: added new arguments and improved functions
\__main\__py: added options to click in accordance with arguments in gisaid_upload.py
> added save receipt.xml in output_path (ena_upload.py) & updated gisaid_upload.py and __main__py

- relecov_tools/__main__.py
- relecov_tools/conf/laboratory_address.json
- relecov_tools/feed_database.py
- relecov_tools/metadata_homogeneizer.py
- relecov_tools/schema/institution_schemas/ISCIII.json
- relecov_tools/utils.py
- requirements.txt
- setup.py
Json structure and coding is created for adding pending information after mapping metadata files to ISCIII format
> handling additional files for metadata_homogenizer module

- relecov_tools/__main__.py
- relecov_tools/conf/configuration.json
- relecov_tools/feed_database.py
- relecov_tools/long_table_parse.py
- relecov_tools/rest_api.py
long table json output did no have the right fomat
https://github.com/BU-ISCIII/relecov-tools/issues/183
> fixed issue 183

- relecov_tools/conf/configuration.json
- relecov_tools/conf/geo_loc_cities.json
- relecov_tools/conf/submitter_address.json
- relecov_tools/metadata_homogeneizer.py
- relecov_tools/read_lab_metadata.py
- relecov_tools/utils.py
- setup.py
Changes also in configuration json to group configurations
> created processed json but without valid enum 

- relecov_tools/schema/relecov_schema.json
Also replace clasification for classification. A 's' was missing
> fixed issue 215

- relecov_tools/__main__.py
- relecov_tools/ena_upload.py
- relecov_tools/institution_scripts/ISCIII.py
- relecov_tools/map_schema.py
- relecov_tools/metadata_homogeneizer.py
- relecov_tools/read_bioinfo_metadata.py
- relecov_tools/sftp_handle.py
- relecov_tools/utils.py
Introduced a new flag to select which folders are going to be downloaded, for which I introduced a checkbox if the flag is given empty. It will still download everything by default if the flag is not given. 
Also, I changed the validation process of the download packages so It's done before downloading everything, using the metadata as reference.  I didn't remove the previous validation method though, so now it should validate the downloaded packages twice.
> Introduced new options to download function

- relecov_tools/conf/laboratory_address.json
- relecov_tools/read_lab_metadata.py
- relecov_tools/sftp_handle.py
- relecov_tools/utils.py
I Included a lot of bug-fixing in [read_lab_metadata.py](https://github.com/BU-ISCIII/relecov-tools/blob/develop/relecov_tools/read_lab_metadata.py) to handle different errors like missing data, incomplete dates or wrong formats for which I also had to fix a "read_excel_file" method in [utils.py](https://github.com/BU-ISCIII/relecov-tools/blob/develop/relecov_tools/utils.py). Also included new addresses in [laboratory_address.json](https://github.com/BU-ISCIII/relecov-tools/blob/develop/relecov_tools/conf/laboratory_address.json) and fixed some comments and logs in [sftp_handle.py](https://github.com/BU-ISCIII/relecov-tools/blob/develop/relecov_tools/sftp_handle.py)
> Fixed read_lab_metadata.py to handle errors like missing data

- relecov_tools/conf/configuration.json
- relecov_tools/feed_database.py
- relecov_tools/long_table_parse.py
- relecov_tools/rest_api.py
- relecov_tools/sftp_handle.py
"sampleName" was not being introduced into json data due to a small error in [feed_database.py](https://github.com/BU-ISCIII/relecov-tools/blob/develop/relecov_tools/feed_database.py), so i proceded to change it along with [configuration.json](https://github.com/BU-ISCIII/relecov-tools/blob/develop/relecov_tools/conf/configuration.json) were I introduced "read_length" as a field in mapping_stats. I also changed "analysis_date" field to match mapping_illumina_stats.tab file. 
Finally, I changed some prints and comments in [long_table_parse.py](https://github.com/BU-ISCIII/relecov-tools/blob/develop/relecov_tools/long_table_parse.py), [rest_api.py](https://github.com/BU-ISCIII/relecov-tools/blob/develop/relecov_tools/rest_api.py) and …
> Fixed missing fields due to error in feed_database.py 

- relecov_tools/conf/geo_loc_cities.json
- relecov_tools/conf/laboratory_address.json
As the title says, due to upcoming data, I included new fields into relecov_tools/conf/geo_loc_cities.json and relecov_tools/conf/laboratory_address.json
> Included new fields into laboratory_address.json and geo_loc.json

- .github/workflows/test_modules.yml
- relecov_tools/conf/anatomical_material_collection_method.json
- relecov_tools/conf/laboratory_address.json
- relecov_tools/schema/relecov_schema.json
This PR has a small fix removing unused github_token variable in `test_modules.yml`, also blood is now correctly added as anatomical_material in `conf/anatomical_material_collection_method.json` and the ontology for body_product has been correctly fixed in `relecov_tools/schema/relecov_schema.json`
> Small fix of tests and blood included in anatomical material

- README.md
Just an update to the README.md regarding the `read-bioinfo-metadata `section.
> update read-bioinfo-metadata readme

- .github/workflows/test_modules.yml
- .github/workflows/test_sftp_handle.yml
Seems like  the changes in #264 were not enough, so I added another parameter to the checkout action in order to fix the error when testing pull-requests.
> Fixed actions pull-requests error again

- relecov_tools/assets/pipeline_utils/viralrecon.py
- relecov_tools/conf/bioinfo_config.json
- relecov_tools/read_bioinfo_metadata.py
This pull request addresses several issues related to the read-bioinfo-metadata module, including the correction of regex patterns and improvements in metadata handling.
-     Fixed regex pattern that caused skipping of sample processing.
-     Resolved black lining issues.
-     Enabled adding software names to processed data.
-     Corrected the assignment of 'software version' fields.
-     Updated regex to properly find file names.
-     Fixed regex error while parsing the date field in the variants long table.
Closes #275
> Fix regex pattern and update metadata handling in read-bioinfo-metadata module

- relecov_tools/json_validation.py
- relecov_tools/log_summary.py
- relecov_tools/read_lab_metadata.py
`LogSum() `class from `log_summary.py `now has two extra arguments, one to define a single key for all the entries and samples in the custom logs `unique_key` and another one to optionally include `path` in the main_key log. The latter should be used to save the path where the processed/validated metadata come from in the json file.
> Updated log_summary.py with new path field and renamed keys

- relecov_tools/__main__.py
- relecov_tools/conf/configuration.json
- relecov_tools/conf/pipeline_config.json
- relecov_tools/launch_pipeline.py
Implemented issue  
#284 Create an option to create simbolic links to Analisys folder
> issue 284.  created new module for pipeline launch

- relecov_tools/assets/pipeline_utils/viralrecon.py
- relecov_tools/download_manager.py
- relecov_tools/read_lab_metadata.py
I standardized the output filenames of the different modules, now including "lab_metadata + lab_code + date and time of execution
> Standardize output filenames

- relecov_tools/pipeline_manager.py
> fix minor bug launch pipeline for copying r2

- CHANGELOG.md
- relecov_tools/download_manager.py
- relecov_tools/sftp_client.py
This PR includes several changes to s`ftp_client.py `and d`ownload_manager.py `
- The download process now includes a check for gzip file integrity after download. 
- Moved cleaning process to the end of the workflow when "download_clean" is activated, so custom logs are always generated prior to removing.
- sftp_client methods now include a decorator that will retry conection to the sftp server when connection is lost before sending an error.
> Check for gzip file integrity, moved cleaning process and new decorator

- CHANGELOG.md
- relecov_tools/conf/laboratory_address.json
Añadido Hospital Universitari Doctor Josep Trueta
> Añadido Hospital Universitari Doctor Josep Trueta

- CHANGELOG.md
- README.md
- relecov_tools/__main__.py
- relecov_tools/conf/configuration.json
- relecov_tools/dataprocess_wrapper.py
- relecov_tools/download_manager.py
- relecov_tools/pipeline_manager.py
- relecov_tools/read_bioinfo_metadata.py
- relecov_tools/read_lab_metadata.py
- relecov_tools/upload_database.py
- setup.py
- FIxed wrong descriptions for wrapper
- Updated README, setup and `__main__`
- Included samples and processed folders in read-bioinfo-metadata log_summary
- improved log readability for upload-database
> Pre-release 1.2.0

- CHANGELOG.md
- relecov_tools/__main__.py
- relecov_tools/conf/configuration.json
- relecov_tools/pipeline_manager.py
- relecov_tools/utils.py
This PR is related to #323, but instead of selecting certain dates. I think it was more convenient to indicate the base-names of the folders that are wanted to be processed, so any folders with these names are merged together. Indicating the date would lead to a big limitation as all the processed folders would be needed to be named with a date in YYYYMMDDHHMMSS format.
Closes #323
> Included new argument to select custom folders in pipeline_manager

- CHANGELOG.md
- relecov_tools/__main__.py
- relecov_tools/conf/configuration.json
- relecov_tools/log_summary.py
- relecov_tools/mail.py
- relecov_tools/templates/jinja_template_mail_sender.j2
- relecov_tools/utils.py
- requirements.txt
This PR implements the automated email notification module as described in issue #317. Closes #317
> Mail sender

- CHANGELOG.md
- relecov_tools/conf/geo_loc_cities.json
- relecov_tools/conf/laboratory_address.json
Corrected the Submitting_institution for Hospital de Valdepeñas, Centro de Salud Altagracia and Hospital General de Santa Bárbara (Ciudad Real). 
Added Hospital General de Tomelloso.
> Corrected the Submitting_institution and added Hospital General de Tomelloso

- CHANGELOG.md
- relecov_tools/conf/configuration.json
- relecov_tools/schema/relecov_schema.json
As per the title, this PR updates the `metadata_processing` field from `configuration.json` and creates the `other_preparation_kit`, `quality_control_metrics` and `consensus_criteria `fields in `relecov_schema.json`.
> Updated configuration.json and the json schema

- CHANGELOG.md
- relecov_tools/assets/schema_utils/jsonschema_draft.py
- relecov_tools/build_schema.py
- relecov_tools/utils.py
- requirements.txt
This PR includes several improvements and fixes related to schema validation and dynamic configuration:
- Fixed validation of mandatory features in schema properties to ensure compliance.
- Enhanced outdir parameter validation.
- Updated schema header to be dynamically populated, improving flexibility.
- Refactored variable names in build_new_schema.
- Fixed linting issues to maintain code quality.
> Improve and fix minor issues in `build_schema.py`  

- CHANGELOG.md
- relecov_tools/__main__.py
- relecov_tools/build_schema.py
- relecov_tools/utils.py
This PR implements a schema summarization method in the build-schema module to provide a structured overview of schema properties and output files using rich tables.
Closes #386
> Add schema summary method to build-schema module

- relecov_tools/utils.py
recover missing function in #391
> Add util function lost in #391

- .github/workflows/python_lint.yml
- CHANGELOG.md
- relecov_tools/__main__.py
- relecov_tools/assets/schema_utils/metadatalab_template.py
- relecov_tools/build_schema.py
- relecov_tools/conf/build_schema_config.json
- relecov_tools/conf/configuration.json
This PR improves `build-schema` module:
- The `build-schema` module has been updated to be project-dependent.
- A new configuration file, `build_schema_config.json`, has been created to manage project-specific settings.
- A new `--project` argument has been added to allow specifying the project.
- The cell formating has been updated to match the new template.
`Organism` has been added to the header of `configuration.json` file, solving issue [#398.](https://github.com/BU-ISCIII/relecov-tools/issues/398)
> Make `build-schema` module project-dependent

- relecov_tools/__main__.py
- relecov_tools/assets/pipeline_utils/viralrecon.py
- relecov_tools/dataprocess_wrapper.py
- relecov_tools/download_manager.py
- relecov_tools/json_validation.py
- relecov_tools/pipeline_manager.py
- relecov_tools/read_bioinfo_metadata.py
- relecov_tools/read_lab_metadata.py
- relecov_tools/sftp_client.py
Reviewed logs:
- wrapper logs
- download logs
- read-lab-metadata logs
- validate logs
- pipeline-manager logs
- read-bioinfo-metadata
- viralrecon
Closes issue #336
> Fixed logs for different modules

- CHANGELOG.md
- relecov_tools/assets/pipeline_utils/create_summary_tables.py
As per the title, the `create_summary_tables.py` is included within the `assets` folder in `relecov_tools`.
> Added create_summary_tables.py to assets

- CHANGELOG.md
- relecov_tools/build_schema.py
- tests/test_wrapper_handle.py
This PR enhances the validation for dropdown columns by notifying users when they enter a value that is not part of the defined options.
> Add Validation for Dropdown Columns: Notify Users of Invalid Entries in `build-schema` module

- CHANGELOG.md
- relecov_tools/__main__.py
As per the title. This PR Closes #444
> Now logs-to-excel also creates a Json file with merged logs

- CHANGELOG.md
- relecov_tools/assets/pipeline_utils/create_summary_tables.py
Changes made so the epidemiological_data.xlsx can be updated weekly with new information which is properly identified with the analysis date. 
Pangolin database and software versions have been added so any change in the lineage assignation can be tracked.
> Added Pangolin Software and Database versions and analysis_date to epidemiological_data.xlsx

- CHANGELOG.md
- relecov_tools/build_schema.py
- relecov_tools/dataprocess_wrapper.py
- relecov_tools/download_manager.py
- relecov_tools/read_bioinfo_metadata.py
- relecov_tools/schema/relecov_schema.json
- tests/test_sftp_modules.py
- tests/test_wrapper_handle.py
This PR updates the quality control (qc_test) evaluation logic in the `read-bioinfo-metadata` module to make it dependent on the project being processed.
> Update Quality Control Test in `read-bioinfo-metadata` to Be Project-Dependent

- CHANGELOG.md
- relecov_tools/base_module.py
- relecov_tools/sftp_client.py
> Hotfix for corrupted folders in sftp 

- CHANGELOG.md
- relecov_tools/dataprocess_wrapper.py
- relecov_tools/schema/relecov_schema.json
- Fix subfolder handling in wrapper
- Update relecov_schema.json
> Fix subfolder handling in wrapper module

- CHANGELOG.md
- relecov_tools/dataprocess_wrapper.py
- relecov_tools/json_validation.py
This PR addresses two issues related to the handling of invalid samples during the wrapper execution:
- Fixes the generation of invalid_*.xlsx files now including header.
- Uploads the generated invalid_*.xlsx instead of the empty template.
> Fix generation and upload of `invalid_*.xlsx` with headers

- CHANGELOG.md
- relecov_tools/conf/configuration.json
- relecov_tools/pipeline_manager.py
This PR introduces support for handling extra metadata templates in the pipeline-manager module.
> Add extra template handling in pipeline-manager

- CHANGELOG.md
- relecov_tools/schema/relecov_schema.json
Three new identifiers have been added to the relecov_schema.json to enhance sample traceability and metadata consistency across the pipeline:
- unique_id: A globally unique identifier for each sample.
- batch_id: Identifies the batch the sample belongs to.
- institution_code: Standardized code representing the submitting institution.
> Add `identifier fields` to `relecov_schema.json`

- CHANGELOG.md
- README.md
- relecov_tools/conf/initial_config.yaml
- relecov_tools/pipeline_manager.py
- I also included small clarifications in `conf/initial_config.yaml` and a bioconda installation guide in `README.md`
> Replaced logs with new BaseModule logging in pipeline-manager

- CHANGELOG.md
- relecov_tools/conf/laboratory_address.json
- relecov_tools/conf/non_sri_adress.json
Added institutions that are not included in SRI to addresses json and created a json file with them for future merging.
Fixes #528
> Added missing laboratory addresses

- CHANGELOG.md
- relecov_tools/conf/anatomical_material_collection_method.json
Closes https://github.com/BU-ISCIII/relecov-tools/issues/518
- anatomical_material_collection.conf was not updated according to the new enums in relecov_schema for specimen source
- This PR updates this file to match the enums there.
- This PR needs update of relecov_schema which is addressed in https://github.com/BU-ISCIII/relecov-tools/pull/563
> Update anatomical material collection conf according to new specimen source

- CHANGELOG.md
- relecov_tools/base_module.py
- relecov_tools/build_schema.py
- relecov_tools/json_validation.py
- relecov_tools/map_schema.py
- relecov_tools/pipeline_manager.py
- relecov_tools/read_bioinfo_metadata.py
- relecov_tools/read_lab_metadata.py
- relecov_tools/upload_database.py
- relecov_tools/upload_ena_protocol.py
- relecov_tools/upload_results.py
> Implemented BaseModule logging in all modules

- CHANGELOG.md
- relecov_tools/conf/configuration.json
This PR addresses issues related to the handling of "Not Provided" in the configuration.json file.
> Fix handling of "Not Provided" in configuration.json

- CHANGELOG.md
- README.md
- pyproject.toml
- relecov_tools/__main__.py
> Pre-release 1.5.1

- CHANGELOG.md
> Hotfix wrong tag changelog

- CHANGELOG.md
- relecov_tools/assets/pipeline_utils/create_summary_tables.py
- relecov_tools/assets/pipeline_utils/irma.py
- relecov_tools/assets/pipeline_utils/viralrecon.py
- relecov_tools/conf/bioinfo_config.json
- relecov_tools/read_bioinfo_metadata.py
- Added all config and scripts needed for influenza analysis.
- Fixed viralrecon properties too
> Add irma and fixed read bioinfo metadata

- CHANGELOG.md
- relecov_tools/schema/relecov_schema.json
This PR updates the relecov_schema.json to version v3.0.7
> Update `relecov_schema.json` to v3.0.7

- CHANGELOG.md
- README.md
- pyproject.toml
- relecov_tools/__main__.py
Pre-release changes for `v1.5.2`
> Pre-release for `v1.5.2`

- CHANGELOG.md
- relecov_tools/schema/relecov_schema.json
Remove *dev from `relecov_schema.json`
> Remove *dev from `relecov_schema.json`

- CHANGELOG.md
> Fix CHANGELOG distribution between releases

- CHANGELOG.md
- README.md
- pyproject.toml
- relecov_tools/__main__.py
> Pre-release `1.5.4`

- CHANGELOG.md
- relecov_tools/base_module.py
- relecov_tools/dataprocess_wrapper.py
- relecov_tools/download_manager.py
- relecov_tools/read_lab_metadata.py
> Fixing wrapper error with empty dir - temp_id log files and empty adding-fields

- CHANGELOG.md
- relecov_tools/__main__.py
- relecov_tools/dataprocess_wrapper.py
- relecov_tools/download_manager.py
- relecov_tools/log_summary.py
- relecov_tools/read_lab_metadata.py
- relecov_tools/upload_database.py
- [] `README.md` is updated (including new tool citations and authors/contributors).
> Use alternative sample IDs when sequencing_sample_id is not provided

- CHANGELOG.md
- relecov_tools/upload_database.py
> Fill missing sample_fields required in iskylims as Not Provided

- CHANGELOG.md
- relecov_tools/__main__.py
- relecov_tools/conf/bioinfo_config.json
- relecov_tools/read_bioinfo_metadata.py
Fixed code to propperly handle new IRMA service folder tree
Fixed issue #634 
Need to test with SARS too
> Fix irma read bioinfo

- CHANGELOG.md
- relecov_tools/__main__.py
> Including error traceback in logfile

- CHANGELOG.md
- relecov_tools/__main__.py
- relecov_tools/assets/pipeline_utils/irma.py
- relecov_tools/assets/pipeline_utils/utils.py
- relecov_tools/assets/pipeline_utils/viralrecon.py
- relecov_tools/conf/bioinfo_config.json
- relecov_tools/read_bioinfo_metadata.py
> Fixed IRMA quality control and json property filtering

- CHANGELOG.md
- README.md
- pyproject.toml
- relecov_tools/__main__.py
- fix output_folder to output_dir in logs to excel #658
> fix output_folder to output_dir in logs to excel

- CHANGELOG.md
- relecov_tools/download_manager.py
The error was not from wrapper, was from download module.
- Fixes #621
> Improve message when error raises while reading metadata excel

- CHANGELOG.md
- pyproject.toml
- relecov_tools/__main__.py
- relecov_tools/assets/mail_templates/template_results_relecov.j2
- relecov_tools/pipeline_manager.py
> minor fix in pipeline_manager so it finds valided json

- .github/workflows/pypi_publish.yml
- .github/workflows/test_modules.yml
- .github/workflows/test_sftp_modules.yml
- CHANGELOG.md
Fix python version on .github/workflows
> Fix python version on .github/workflows

- CHANGELOG.md
- README.md
- pyproject.toml
- relecov_tools/__main__.py
- relecov_tools/download.py
Check `.~lock` files in before downloading. If a lock file is detected (without the valid xlsx in the remote dir) an exception raises.
> pre-release v1.6.2 & check `.~lock` files in download

- CHANGELOG.md
- relecov_tools/assets/pipeline_utils/create_summary_tables.py
As per the title, this PR updates the `create_summary_tables.py` script to generate surveillance results as requested:
* The epidemiological data table remains global, containing information for all the analyzed samples. New columns are added.
* From now on, variant data and consensus files are stored in their corresponding season subfolders.
> Updated SARS surveillance script

- CHANGELOG.md
- README.md
- pyproject.toml
- relecov_tools/__main__.py
- relecov_tools/conf/configuration.json
- relecov_tools/pipeline_manager.py
- relecov_tools/upload_database.py
- relecov_tools/utils.py
- relecov_tools/validate.py
This pull request introduces major updates to `validate`, `upload_database`, and `pipeline_manager` modules to improve consistency, configurability, and robustness of sample handling and metadata uploads across platforms.
- Reordered class initializations as described in issue #692 for improved consistency and clarity.
- Now supports direct duplicate checking in the database via `RestApi`, skipping validation if the sample already exists (`#737`).
- Replaced custom `config` usage with standard `ConfigJson` class.
- Added support for uploading samples to the database from `pipeline_manager`, retrieving and storing the `unique_sample_id` into `json_data` (`#737`).
- Introduced `skip_upload_db` parameter for easier testing and control.
- File renaming now uses `unique_sample_id` as the …
> Enhancements related to issue737 and issue 738

- CHANGELOG.md
- relecov_tools/upload_results.py
> Add project name to email subject in upload_results

- CHANGELOG.md
The template for the next version has been removed from the pre-release PR
> Remove Template from CHANGELOG

- relecov_tools/schema/relecov_schema.json
> Minor id schema fix

- CHANGELOG.md
- relecov_tools/assets/template_utils/check-UCCT.py
- relecov_tools/conf/configuration.json
This PR introduces a new analytics utility for UCCT tracking and updates the platform payload to include the lab code.
Process the `UCCT_Relecov_Status` file to generate per-laboratory statistics of submitted samples.
- Parses the UCCT status workbook and aggregates
- Samples per laboratory
The upload/submit configuration now adds `collecting_institution_code_1`
> Add UCCT status analytics script & send collecting_institution_code_1 to Relecov Platform
